// ============================================================
//  Banco de dados compartilhado do TechFix
//  Todos os clientes, equipamentos e ordens de serviço ficam
//  aqui para que todas as páginas mostrem os mesmos dados.
// ============================================================

export const clientes = [
  { id: 1, codigo: "CLI-0012", nome: "Maria Silva",    telefone: "(68) 99999-1234", email: "maria.silva@email.com",    cidade: "Rio Branco",         equipamentos: 3, status: "Ativo" },
  { id: 2, codigo: "CLI-0013", nome: "João Pereira",  telefone: "(68) 98888-5678", email: "joao.pereira@email.com",  cidade: "Rio Branco",         equipamentos: 1, status: "Ativo" },
  { id: 3, codigo: "CLI-0014", nome: "Ana Costa",     telefone: "(68) 97777-9012", email: "ana.costa@email.com",     cidade: "Senador Guiomard",   equipamentos: 2, status: "Ativo" },
  { id: 4, codigo: "CLI-0015", nome: "Carlos Souza",  telefone: "(68) 96666-3456", email: "carlos.souza@email.com",  cidade: "Rio Branco",         equipamentos: 4, status: "Inativo" },
  { id: 5, codigo: "CLI-0016", nome: "Fernanda Lima", telefone: "(68) 95555-7890", email: "fernanda.lima@email.com", cidade: "Plácido de Castro",  equipamentos: 1, status: "Ativo" },
  { id: 6, codigo: "CLI-0017", nome: "Roberto Alves", telefone: "(68) 94444-2345", email: "roberto.alves@email.com", cidade: "Rio Branco",         equipamentos: 2, status: "Ativo" },
  { id: 7, codigo: "CLI-0018", nome: "Lucas Souza",   telefone: "(68) 93333-1122", email: "lucas.souza@email.com",   cidade: "Rio Branco",         equipamentos: 1, status: "Ativo" },
  { id: 8, codigo: "CLI-0019", nome: "Pedro Mendes",  telefone: "(68) 92222-9988", email: "pedro.mendes@email.com",  cidade: "Acrelândia",         equipamentos: 1, status: "Ativo" },
  { id: 9, codigo: "CLI-0020", nome: "Julia Rocha",   telefone: "(68) 91111-7766", email: "julia.rocha@email.com",   cidade: "Rio Branco",         equipamentos: 1, status: "Ativo" },
];

export const equipamentos = [
  { id: "EQ-0012", tipo: "Notebook",    marca: "Dell",     modelo: "Inspiron 15 3511",  serial: "DL2024X991",  codigoCliente: "CLI-0012", cliente: "Maria Silva",    defeito: "Não liga",                   status: "Em reparo" },
  { id: "EQ-0013", tipo: "Smartphone",  marca: "Samsung",  modelo: "Galaxy A54",         serial: "SM-A546B22",  codigoCliente: "CLI-0013", cliente: "João Pereira",   defeito: "Tela trincada",              status: "Aguardando peça" },
  { id: "EQ-0014", tipo: "Impressora",  marca: "HP",       modelo: "LaserJet M404",      serial: "HP404-88321", codigoCliente: "CLI-0014", cliente: "Ana Costa",      defeito: "Atolamento de papel",        status: "Na fila" },
  { id: "EQ-0015", tipo: "Desktop",     marca: "Positivo", modelo: "Master D3400",       serial: "PS-D3400-77", codigoCliente: "CLI-0015", cliente: "Carlos Souza",   defeito: "Superaquecimento",           status: "Em reparo" },
  { id: "EQ-0016", tipo: "Tablet",      marca: "Apple",    modelo: "iPad 9ª Geração",    serial: "IPD9-44120",  codigoCliente: "CLI-0016", cliente: "Fernanda Lima",  defeito: "Bateria descarrega rápido",  status: "Pronto" },
  { id: "EQ-0017", tipo: "Console",     marca: "Sony",     modelo: "PlayStation 5",      serial: "PS5-00912-BR",codigoCliente: "CLI-0017", cliente: "Roberto Alves",  defeito: "Sem imagem (HDMI)",          status: "Em reparo" },
  { id: "EQ-0018", tipo: "Smartphone",  marca: "iphone",   modelo: "11",                 serial: "IPH11-5582",  codigoCliente: "CLI-0018", cliente: "Lucas Souza",    defeito: "Não carrega",                status: "Aguardando peça" },
  { id: "EQ-0019", tipo: "Smartphone",  marca: "iphone",   modelo: "16 pro max",         serial: "IPH16-9921",  codigoCliente: "CLI-0019", cliente: "Pedro Mendes",   defeito: "Microfone mudo",             status: "Pronto" },
  { id: "EQ-0020", tipo: "Smartphone",  marca: "iPhone",   modelo: "17 Pro Max",         serial: "IPH17-1029",  codigoCliente: "CLI-0020", cliente: "Julia Rocha",    defeito: "Face ID falhando",           status: "Na fila" },
  { id: "EQ-0021", tipo: "Smartphone",  marca: "Motorola", modelo: "Edge 40",            serial: "MOT-8812A",   codigoCliente: "CLI-0012", cliente: "Maria Silva",    defeito: "Câmera borrada",             status: "Em reparo" },
  { id: "EQ-0022", tipo: "Notebook",    marca: "Apple",    modelo: "MacBook Pro M2",     serial: "MAC-99882X",  codigoCliente: "CLI-0013", cliente: "João Pereira",   defeito: "Teclado falhando",           status: "Aguardando peça" },
];

export const ordensDeServico = [
  {
    numero: "OS-2026-0142",
    codigoCliente: "CLI-0012",
    cliente: "Maria Silva",
    telefone: "(68) 99999-1234",
    equipamento: "Dell Inspiron 15 3511",
    servico: "Troca de placa-mãe",
    tecnico: "Rafael M.",
    previsao: "28/08/2026",
    valor: "R$ 680,00",
    status: "Em reparo",
    etapas: [
      { label: "OS registrada",        data: "20/08/2026 09:14", feito: true,  atual: false },
      { label: "Diagnóstico concluído",data: "21/08/2026 15:40", feito: true,  atual: false },
      { label: "Orçamento aprovado",   data: "22/08/2026 10:02", feito: true,  atual: false },
      { label: "Em reparo",            data: "24/08/2026 08:30", feito: true,  atual: true  },
      { label: "Testes finais",        data: "—",                feito: false, atual: false },
      { label: "Pronto para retirada", data: "—",                feito: false, atual: false },
    ],
  },
  {
    numero: "OS-2026-0143",
    codigoCliente: "CLI-0016",
    cliente: "Fernanda Lima",
    telefone: "(68) 95555-7890",
    equipamento: "Apple iPad 9ª Geração",
    servico: "Troca de bateria",
    tecnico: "Carlos T.",
    previsao: "25/08/2026",
    valor: "R$ 350,00",
    status: "Pronto",
    etapas: [
      { label: "OS registrada",        data: "19/08/2026 10:00", feito: true, atual: false },
      { label: "Diagnóstico concluído",data: "19/08/2026 14:20", feito: true, atual: false },
      { label: "Orçamento aprovado",   data: "20/08/2026 09:15", feito: true, atual: false },
      { label: "Em reparo",            data: "21/08/2026 11:30", feito: true, atual: false },
      { label: "Testes finais",        data: "22/08/2026 16:45", feito: true, atual: false },
      { label: "Pronto para retirada", data: "23/08/2026 09:00", feito: true, atual: true  },
    ],
  },
  {
    numero: "OS-2026-0144",
    codigoCliente: "CLI-0013",
    cliente: "João Pereira",
    telefone: "(68) 98888-5678",
    equipamento: "Samsung Galaxy A54",
    servico: "Troca de tela",
    tecnico: "Rafael M.",
    previsao: "27/08/2026",
    valor: "R$ 420,00",
    status: "Aguardando peça",
    etapas: [
      { label: "OS registrada",        data: "22/08/2026 08:30", feito: true,  atual: false },
      { label: "Diagnóstico concluído",data: "22/08/2026 11:00", feito: true,  atual: false },
      { label: "Orçamento aprovado",   data: "22/08/2026 14:10", feito: true,  atual: false },
      { label: "Aguardando peça",      data: "24/08/2026 09:00", feito: true,  atual: true  },
      { label: "Em reparo",            data: "—",                feito: false, atual: false },
      { label: "Testes finais",        data: "—",                feito: false, atual: false },
      { label: "Pronto para retirada", data: "—",                feito: false, atual: false },
    ],
  },
  {
    numero: "OS-2026-0145",
    codigoCliente: "CLI-0018",
    cliente: "Lucas Souza",
    telefone: "(68) 93333-1122",
    equipamento: "iphone 11",
    servico: "Substituição do conector de carga",
    tecnico: "Carlos T.",
    previsao: "26/08/2026",
    valor: "R$ 180,00",
    status: "Aguardando peça",
    etapas: [
      { label: "OS registrada",        data: "25/08/2026 09:00", feito: true,  atual: false },
      { label: "Diagnóstico concluído",data: "25/08/2026 10:30", feito: true,  atual: false },
      { label: "Orçamento aprovado",   data: "25/08/2026 14:00", feito: true,  atual: true  },
      { label: "Aguardando peça",      data: "—",                feito: false, atual: false },
      { label: "Em reparo",            data: "—",                feito: false, atual: false },
      { label: "Pronto para retirada", data: "—",                feito: false, atual: false },
    ],
  },
  {
    numero: "OS-2026-0151",
    codigoCliente: "CLI-0017",
    cliente: "Roberto Alves",
    telefone: "(68) 94444-2345",
    equipamento: "Sony PlayStation 5",
    servico: "Troca de HDMI",
    tecnico: "Carlos T.",
    previsao: "29/08/2026",
    valor: "R$ 290,00",
    status: "Em reparo",
    etapas: [
      { label: "OS registrada",        data: "23/08/2026 10:00", feito: true,  atual: false },
      { label: "Diagnóstico concluído",data: "23/08/2026 14:30", feito: true,  atual: false },
      { label: "Orçamento aprovado",   data: "24/08/2026 09:00", feito: true,  atual: false },
      { label: "Em reparo",            data: "25/08/2026 11:00", feito: true,  atual: true  },
      { label: "Testes finais",        data: "—",                feito: false, atual: false },
      { label: "Pronto para retirada", data: "—",                feito: false, atual: false },
    ],
  },
  {
    numero: "OS-2026-0146",
    codigoCliente: "CLI-0018",
    cliente: "Lucas Souza",
    telefone: "(68) 93333-1122",
    equipamento: "iphone 11",
    servico: "Substituição do conector de carga",
    tecnico: "Carlos T.",
    previsao: "26/08/2026",
    valor: "R$ 180,00",
    status: "Aguardando peça",
    etapas: [
      { label: "OS registrada",        data: "25/08/2026 09:00", feito: true,  atual: false },
      { label: "Diagnóstico concluído",data: "25/08/2026 10:30", feito: true,  atual: false },
      { label: "Orçamento aprovado",   data: "25/08/2026 14:00", feito: true,  atual: true  },
      { label: "Aguardando peça",      data: "—",                feito: false, atual: false },
      { label: "Em reparo",            data: "—",                feito: false, atual: false },
      { label: "Pronto para retirada", data: "—",                feito: false, atual: false },
    ],
  },
  {
    numero: "OS-2026-0147",
    codigoCliente: "CLI-0019",
    cliente: "Pedro Mendes",
    telefone: "(68) 92222-9988",
    equipamento: "iphone 16 pro max",
    servico: "Troca de microfone",
    tecnico: "Rafael M.",
    previsao: "27/08/2026",
    valor: "R$ 250,00",
    status: "Pronto",
    etapas: [
      { label: "OS registrada",        data: "20/08/2026 08:00", feito: true, atual: false },
      { label: "Diagnóstico concluído",data: "20/08/2026 11:00", feito: true, atual: false },
      { label: "Orçamento aprovado",   data: "21/08/2026 09:30", feito: true, atual: false },
      { label: "Em reparo",            data: "22/08/2026 10:00", feito: true, atual: false },
      { label: "Testes finais",        data: "23/08/2026 15:00", feito: true, atual: false },
      { label: "Pronto para retirada", data: "24/08/2026 09:00", feito: true, atual: true  },
    ],
  },
  {
    numero: "OS-2026-0148",
    codigoCliente: "CLI-0020",
    cliente: "Julia Rocha",
    telefone: "(68) 91111-7766",
    equipamento: "iPhone 17 Pro Max",
    servico: "Reparo de Face ID",
    tecnico: "Rafael M.",
    previsao: "30/08/2026",
    valor: "R$ 480,00",
    status: "Na fila",
    etapas: [
      { label: "OS registrada",        data: "26/08/2026 09:00", feito: true,  atual: true  },
      { label: "Diagnóstico concluído",data: "—",                feito: false, atual: false },
      { label: "Orçamento aprovado",   data: "—",                feito: false, atual: false },
      { label: "Em reparo",            data: "—",                feito: false, atual: false },
      { label: "Testes finais",        data: "—",                feito: false, atual: false },
      { label: "Pronto para retirada", data: "—",                feito: false, atual: false },
    ],
  },
  {
    numero: "OS-2026-0149",
    codigoCliente: "CLI-0014",
    cliente: "Ana Costa",
    telefone: "(68) 97777-9012",
    equipamento: "HP LaserJet M404",
    servico: "Limpeza e desobstrução de papel",
    tecnico: "Carlos T.",
    previsao: "28/08/2026",
    valor: "R$ 120,00",
    status: "Na fila",
    etapas: [
      { label: "OS registrada",        data: "26/08/2026 10:00", feito: true,  atual: true  },
      { label: "Diagnóstico concluído",data: "—",                feito: false, atual: false },
      { label: "Orçamento aprovado",   data: "—",                feito: false, atual: false },
      { label: "Em reparo",            data: "—",                feito: false, atual: false },
      { label: "Pronto para retirada", data: "—",                feito: false, atual: false },
    ],
  },
  {
    numero: "OS-2026-0150",
    codigoCliente: "CLI-0015",
    cliente: "Carlos Souza",
    telefone: "(68) 96666-3456",
    equipamento: "Positivo Master D3400",
    servico: "Limpeza interna e troca de pasta térmica",
    tecnico: "Rafael M.",
    previsao: "29/08/2026",
    valor: "R$ 160,00",
    status: "Em reparo",
    etapas: [
      { label: "OS registrada",        data: "22/08/2026 13:00", feito: true,  atual: false },
      { label: "Diagnóstico concluído",data: "22/08/2026 16:00", feito: true,  atual: false },
      { label: "Orçamento aprovado",   data: "23/08/2026 10:00", feito: true,  atual: false },
      { label: "Em reparo",            data: "25/08/2026 09:00", feito: true,  atual: true  },
      { label: "Testes finais",        data: "—",                feito: false, atual: false },
      { label: "Pronto para retirada", data: "—",                feito: false, atual: false },
    ],
  },
];
